app = "revey-api"
primary_region = "sin"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  min_machines_running = 1

[[services.http_checks]]
  path = "/api/health"
